# Generated by Django 5.2 on 2026-01-28 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=50)),
                ('home_ground', models.CharField(max_length=100)),
                ('contact_pref', models.CharField(max_length=50)),
                ('badge_url', models.URLField(blank=True)),
                ('last_search_config', models.TextField(blank=True)),
                ('last_search_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_position', models.CharField(max_length=50)),
                ('secondary_position', models.CharField(blank=True, max_length=50)),
                ('preferred_foot', models.CharField(max_length=10)),
                ('height_cm', models.IntegerField(blank=True, null=True)),
                ('experience_level', models.CharField(max_length=50)),
                ('availability_window', models.CharField(max_length=100)),
                ('locality_area', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('visibility', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
