# Generated by Django 5.2 on 2026-01-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='availability_window',
            field=models.CharField(choices=[('WKD', 'Weekends'), ('WK', 'Weekdays'), ('EVE', 'Evenings'), ('ANY', 'Any availability')], max_length=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='experience_level',
            field=models.CharField(choices=[('YTH', 'Youth / Academy'), ('AM', 'Amateur'), ('SEMI', 'Semi-Professional'), ('PRO', 'Professional')], max_length=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='locality_area',
            field=models.CharField(choices=[('N', 'North London'), ('NE', 'North-East London'), ('NW', 'North-West London'), ('E', 'East London'), ('SE', 'South-East London'), ('SW', 'South-West London'), ('W', 'West London'), ('S', 'South London'), ('C', 'Central London')], max_length=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Both')], max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='primary_position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('CB', 'Centre Back'), ('DM', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('AM', 'Attacking Midfielder'), ('RW', 'Right Winger'), ('LW', 'Left Winger'), ('ST', 'Striker')], max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='secondary_position',
            field=models.CharField(blank=True, choices=[('GK', 'Goalkeeper'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('CB', 'Centre Back'), ('DM', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('AM', 'Attacking Midfielder'), ('RW', 'Right Winger'), ('LW', 'Left Winger'), ('ST', 'Striker')], max_length=3),
        ),
    ]
