# Generated by Django 5.2 on 2026-01-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_player_availability_window_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='last_search_at',
        ),
        migrations.RemoveField(
            model_name='club',
            name='last_search_config',
        ),
        migrations.AlterField(
            model_name='club',
            name='contact_pref',
            field=models.CharField(choices=[('in_app', 'In-app only'), ('email', 'Email'), ('phone', 'Phone')], max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='division',
            field=models.CharField(choices=[('sunday_league', 'Sunday League'), ('amateur', 'Amateur'), ('semi_pro', 'Semi-Professional'), ('academy', 'Academy'), ('grassroots', 'Grassroots')], max_length=30),
        ),
    ]
