# Generated by Django 5.2 on 2026-02-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_club_last_search_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
