# Generated by Django 5.2 on 2026-04-10 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist_entries', to='core.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='core.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('club', 'player'), name='unique_club_player_shortlist')],
            },
        ),
    ]
