# Generated by Django 5.2 on 2026-04-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_shortlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='last_search_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='last_search_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
