# Generated by Django 5.2 on 2026-04-10 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_club_last_search_at_club_last_search_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialrequest',
            name='outcome',
            field=models.CharField(blank=True, choices=[('', 'Not recorded'), ('offered', 'Offered a place'), ('not_offered', 'Not offered a place'), ('no_show', 'Did not attend')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='trialrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TrialFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positional_suitability', models.CharField(blank=True, choices=[('strong', 'Strong'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs improvement')], max_length=20)),
                ('work_rate', models.CharField(blank=True, choices=[('strong', 'Strong'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs improvement')], max_length=20)),
                ('decision_making', models.CharField(blank=True, choices=[('strong', 'Strong'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs improvement')], max_length=20)),
                ('offer_decision', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('club_comment', models.TextField(blank=True)),
                ('generated_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.trialrequest')),
            ],
        ),
    ]
