# Generated by Django 5.2 on 2026-04-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_trialrequest_outcome_alter_trialrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialfeedback',
            name='physicality',
            field=models.CharField(blank=True, choices=[('strong', 'Strong'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs improvement'), ('not_good', 'Not good')], max_length=20),
        ),
        migrations.AddField(
            model_name='trialfeedback',
            name='teammate_understanding',
            field=models.CharField(blank=True, choices=[('strong', 'Strong'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs improvement'), ('not_good', 'Not good')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trialfeedback',
            name='decision_making',
            field=models.CharField(blank=True, choices=[('strong', 'Strong'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs improvement'), ('not_good', 'Not good')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trialfeedback',
            name='positional_suitability',
            field=models.CharField(blank=True, choices=[('strong', 'Strong'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs improvement'), ('not_good', 'Not good')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trialfeedback',
            name='work_rate',
            field=models.CharField(blank=True, choices=[('strong', 'Strong'), ('satisfactory', 'Satisfactory'), ('needs_improvement', 'Needs improvement'), ('not_good', 'Not good')], max_length=20),
        ),
    ]
