# Generated by Django 5.2 on 2026-04-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_trialfeedback_physicality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='badge_url',
        ),
        migrations.AddField(
            model_name='club',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='club',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='contact_pref',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=20),
        ),
    ]
