# Generated by Django 5.2 on 2026-04-11 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_club_badge_url_club_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('trial_invitation', 'Trial Invitation'), ('feedback', 'Feedback'), ('player_profile', 'Player Profile')], max_length=30)),
                ('reason', models.CharField(choices=[('suspicious_invitation', 'Suspicious invitation'), ('inappropriate_trial_details', 'Inappropriate trial details'), ('suspected_fake_club', 'Suspected fake club'), ('abusive_communication', 'Abusive or unprofessional communication'), ('unfair_feedback', 'Feedback appears misleading or unfair'), ('inappropriate_language', 'Inappropriate language'), ('suspected_fake_profile', 'Suspected fake profile'), ('misleading_profile', 'Misleading player information'), ('inappropriate_profile_content', 'Inappropriate profile content'), ('abusive_behaviour', 'Abusive behaviour'), ('other', 'Other')], max_length=40)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.trialfeedback')),
                ('reported_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_against', to='core.player')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('resolver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
                ('trial_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.trialrequest')),
            ],
        ),
    ]
