# Generated by Django 5.2 on 2026-04-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='player',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
