# Generated by Django 5.2 on 2026-04-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_player_contact_email_player_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
